name: XOR Secret Leak

on: push

jobs:
  xor_secret:
    runs-on: ubuntu-latest
    env:
      SECRET: ${{ secrets.MY_SECRET }}
    steps:
      - name: XOR the secret and print
        run: |
          KEY="A"  # simple 1-char XOR key
          xor() {
            local input="$1"
            local key="$2"
            local output=""
            for (( i=0; i<${#input}; i++ )); do
              char="${input:$i:1}"
              xor_char=$(printf '%d' "'$char")
              xor_key=$(printf '%d' "'$key")
              result=$(( xor_char ^ xor_key ))
              output+=$(printf '\\x%02x' "$result")
            done
            echo -e "$output"
          }

          echo "XOR'd secret:"
          xor "$SECRET" "$KEY"
