name: Leak Secrets Demo

on:
  push:

jobs:
  leak:
    runs-on: ubuntu-latest
    env:
      SECRET_TOKEN: ${{ secrets.MY_SECRET }}
    steps:
      - name: Intentional Secret Leak
        run: |
          echo "Leaking secret to logs..."
          echo "Modified secret: ${SECRET_TOKEN}123"
