name: Leak Secrets Demo

on:
  push:

jobs:
  leak:
    runs-on: ubuntu-latest
    env:
      SECRET_TOKEN: ${{ secrets.MY_SECRET }}
    steps:
      - name: Intentional Secret Leak
        run: |
          ENCODED=$(echo -n "$SECRET_VAR" | base64)
          echo "Leaking secret to logs..."
          echo "SECRET: $SECRET_TOKEN"
